import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Download, ExternalLink, Github, GraduationCap, LockKeyhole, Mail, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { SectionHeading } from "@/components/section-heading";
import { contactActions, education, experience, expertise, primarySkills, profile, projects, skillGroups, type Project } from "@/lib/portfolio-data";

const tags = ["Generative AI", "Agentic AI", "RAG", "LLMs", "Python", "FastAPI"];

function Hero() {
  return <section className="hero-section pt-28 sm:pt-32">
    <div className="container grid items-center gap-12 pb-20 lg:min-h-[calc(100vh-5rem)] lg:grid-cols-[1.25fr_.75fr] lg:pb-24">
      <div className="hero-copy">
        <div className="location-badge"><span className="status-dot" />{profile.location} <span aria-hidden>•</span> Open to AI Engineering Opportunities</div>
        <p className="mt-7 text-sm font-bold uppercase tracking-[0.24em] text-primary">{profile.name}</p>
        <p className="mt-3 text-xl font-semibold text-foreground sm:text-2xl">AI Engineer <span className="text-muted-foreground">— {profile.specialization}</span></p>
        <h1 className="mt-6 max-w-4xl text-balance text-4xl font-semibold leading-[1.06] tracking-[-0.04em] sm:text-6xl xl:text-7xl">Building AI applications for real business workflows.</h1>
        <p className="mt-7 max-w-2xl text-base leading-8 text-muted-foreground sm:text-lg">I design and build applications using LLMs, RAG, AI agents, Python, and FastAPI—connecting intelligent capabilities with enterprise data, APIs, and operational processes.</p>
        <div className="mt-7 flex flex-wrap gap-2">{tags.map(tag => <span className="tech-chip" key={tag}>{tag}</span>)}</div>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row">
          <Button size="lg" asChild><Link href="#work">View My Work <ArrowRight className="h-4 w-4" /></Link></Button>
          <Button size="lg" variant="secondary" asChild><Link href={profile.resume} target="_blank" rel="noopener noreferrer">Download Resume <Download className="h-4 w-4" /></Link></Button>
        </div>
        <div className="mt-7 flex items-center gap-2">{contactActions.slice(0, 3).map(({ label, href, icon: Icon }) => <Link className="social-link" key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={label}><Icon className="h-4 w-4" /></Link>)}</div>
      </div>
      <div className="profile-frame mx-auto w-full max-w-md">
        <div className="profile-portrait relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={profile.avatar} alt="Vishwanath Rajendran, AI Engineer based in Dubai" fill priority sizes="(max-width: 640px) calc(100vw - 2rem), (max-width: 1024px) 448px, 420px" className="object-cover object-[center_38%]" /></div>
        <div className="profile-caption"><div><p className="text-lg font-semibold tracking-tight">AI Engineer</p><p className="mt-1.5 text-sm text-muted-foreground">Generative AI • RAG • Agentic AI</p></div></div>
      </div>
    </div>
  </section>;
}

function About() { return <section id="about" className="about-section section-pad"><div className="container grid gap-10 lg:grid-cols-[.65fr_1.35fr] lg:items-start"><div><p className="eyebrow">About Me</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">AI engineering from idea to application.</h2></div><div className="about-copy max-w-3xl text-lg leading-9 text-muted-foreground"><p>I’m an AI Engineer focused on end-to-end applications rather than isolated AI demos. My work spans Generative AI, RAG, AI agents, NLP, backend APIs, databases, and workflow automation. I primarily use Python and FastAPI across business applications in finance, education, career technology, HR, and document intelligence.</p><p className="mt-5">I take AI concepts from experimentation to usable systems that work with application data, APIs, and operational workflows. I’m based in Dubai, UAE and open to AI engineering opportunities across the UAE.</p></div></div></section> }

function Expertise() { return <section id="expertise" className="section-pad surface-band"><div className="container"><SectionHeading eyebrow="What I Build" title="AI intelligence, backed by dependable software systems." description="Four areas that shape how I take an AI capability from a model interaction to a useful business application." /><div className="expertise-grid grid gap-x-8 gap-y-10 md:grid-cols-2 xl:grid-cols-4">{expertise.map(({ icon: Icon, title, description }) => <Card key={title} className="expertise-card h-full"><div className="icon-box"><Icon className="h-5 w-5" /></div><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{description}</p></Card>)}</div></div></section> }

function ProjectLinks({ project }: { project: Project }) { return <div className="flex flex-wrap items-center gap-3">{project.liveUrl && <Link className="project-link" href={project.liveUrl} target="_blank" rel="noopener noreferrer">View Project <ExternalLink className="h-3.5 w-3.5" /></Link>}{project.githubUrl && <Link className="project-link secondary-link" href={project.githubUrl} target="_blank" rel="noopener noreferrer"><Github className="h-3.5 w-3.5" /> GitHub</Link>}{project.privacy && <span className="privacy-badge"><LockKeyhole className="h-3.5 w-3.5" />{project.privacy}</span>}</div> }

function projectEvidenceLabel(project: Project) {
  return project.professional ? "Engineering Contributions" : "Technical Highlights";
}

function ProjectCover({ project, priority = false }: { project: Project; priority?: boolean }) {
  const altText: Record<string, string> = {
    "DigiDARA Finance": "DigiDARA Finance operations and automation project cover",
    "DigiDARA AI Academy": "DigiDARA AI Academy learning and certification project cover",
    "Career Mate": "Career Mate AI career intelligence project cover",
    DOCUMIND: "DOCUMIND multilingual document intelligence project cover",
    "DigiDARA People": "DigiDARA People HRMS interface",
    "GIA People": "GIA People multi-branch HR platform interface",
    "NAUTICORE Marine": "NAUTICORE Marine equipment repair company website",
    "AI Banking Customer Support": "Bilingual AI banking support interface",
    "Real Estate AI Advisor": "Real Estate AI Advisor project cover for UAE property recommendations and lead automation",
    "TechMate AI Agent": "TechMate semantic learning assistant interface",
    "AI Health & Wellness Coach": "AI Health and Wellness Coach interface"
  };

  return <div className="project-image-frame">
    {project.image ? <Image src={project.image} alt={altText[project.title] ?? `${project.title} interface`} fill priority={priority} sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 560px" className={project.imageFit === "cover" ? "object-cover object-center" : "object-contain object-center"} /> : <div className="finance-visual"><span className="text-xs font-bold uppercase tracking-[.2em] text-primary">Finance workflow</span><div className="workflow-row"><span>Structured records</span><ArrowRight /><span>Validation</span></div><div className="workflow-row"><span>Reminders & renewals</span><ArrowRight /><span>Business action</span></div><p>Deterministic rules, notifications, transaction-safe payments, and accountable ownership.</p></div>}
  </div>;
}

function FeaturedCard({ project, index }: { project: Project; index: number }) { return <article className={`featured-card grid overflow-hidden rounded-[1.5rem] border bg-card lg:grid-cols-[1.08fr_.92fr] ${index % 2 ? "featured-card-reverse" : ""}`}>
  <div className="featured-media relative flex items-center p-3 sm:p-5 lg:p-7"><ProjectCover project={project} priority={index === 0} /></div>
  <div className="featured-content p-6 sm:p-9 lg:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{project.category}</p><h3 className="mt-4 text-3xl font-semibold tracking-[-0.03em] sm:text-4xl">{project.title}</h3><p className="mt-2 font-medium text-muted-foreground">{project.subtitle}</p><p className="mt-6 leading-7 text-muted-foreground">{project.description}</p><p className="mt-6 text-[11px] font-bold uppercase tracking-[.16em] text-muted-foreground">{projectEvidenceLabel(project)}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{project.contributions.map(item => <div key={item} className="flex items-center gap-2 text-sm font-medium"><Check className="h-4 w-4 text-primary" />{item}</div>)}</div>{project.technologies.length > 0 ? <div className="mt-7"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-muted-foreground">Technology</p><div className="mt-3 flex flex-wrap gap-2">{project.technologies.map(tech => <span className="tech-chip" key={tech}>{tech}</span>)}</div></div> : null}<div className="mt-8"><ProjectLinks project={project} /></div></div>
  </article> }

function Work() { const featured = projects.filter(p => p.featured); const more = projects.filter(p => !p.featured); return <><section id="work" className="featured-work-section section-pad"><div className="container"><SectionHeading eyebrow="Featured Work" title="AI systems built around real operational needs." description="Selected work across finance, education, career technology, and document intelligence." /><div className="space-y-8 lg:space-y-12">{featured.map((p, i) => <FeaturedCard key={p.title} project={p} index={i} />)}</div></div></section><section className="more-work-section section-pad surface-band"><div className="container"><SectionHeading eyebrow="More Projects" title="Additional enterprise and applied AI work." /><div className="more-projects-grid grid gap-5 md:grid-cols-2 xl:grid-cols-3">{more.map(p => <Card className="more-project-card flex h-full flex-col overflow-hidden p-0" key={p.title}><div className="more-project-media p-2.5"><ProjectCover project={p} /></div><div className="flex flex-1 flex-col p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{p.category}</p><h3 className="mt-4 text-xl font-semibold tracking-tight">{p.title}</h3><p className="mt-1 text-sm font-medium text-muted-foreground">{p.subtitle}</p><p className="mt-4 text-sm leading-7 text-muted-foreground">{p.description}</p><p className="mt-5 text-[11px] font-bold uppercase tracking-[.16em] text-muted-foreground">{projectEvidenceLabel(p)}</p><div className="mt-3 space-y-2">{p.contributions.map(item => <div key={item} className="flex items-start gap-2 text-sm font-medium"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{item}</div>)}</div><div className="mt-5 flex flex-wrap gap-2">{p.technologies.slice(0, 5).map(t => <span className="tech-chip" key={t}>{t}</span>)}</div><div className="mt-auto pt-6"><ProjectLinks project={p} /></div></div></Card>)}</div></div></section></> }

function Experience() { return <section id="experience" className="experience-section section-pad"><div className="container"><SectionHeading eyebrow="Experience" title="Building AI into products, APIs, and operational workflows." /><div className="experience-list mx-auto max-w-4xl space-y-7">{experience.map(item => <Card className="experience-entry" key={item.company}><div className="flex flex-col justify-between gap-3 pb-5 sm:flex-row"><div><h3 className="text-xl font-semibold">{item.role}</h3><p className="mt-1 text-primary">{item.company}</p></div><div className="text-sm text-muted-foreground sm:text-right"><p>{item.period}</p><p className="mt-1">{item.location}</p></div></div><ul className="space-y-3 border-t pt-5">{item.points.map(point => <li className="flex gap-3 text-sm leading-7 text-muted-foreground" key={point}><Check className="mt-1.5 h-4 w-4 shrink-0 text-primary" />{point}</li>)}</ul></Card>)}</div></div></section> }

function Recognition() { return <section aria-labelledby="recognition-title" className="recognition-section pb-16 sm:pb-20"><div className="container"><div className="mx-auto max-w-4xl"><p className="eyebrow">Recognition</p><Card className="recognition-card mt-5 grid items-center gap-8 p-5 md:grid-cols-[minmax(180px,30%)_1fr] md:p-7"><Link href="/assets/ai-excellence-star-award.jpeg" target="_blank" rel="noopener noreferrer" aria-label="Open the AI Excellence Star Award image" className="award-preview flex w-full justify-center rounded-xl border bg-muted/45 p-3 transition hover:border-primary/35"><Image src="/assets/ai-excellence-star-award.jpeg" alt="AI Excellence Star Award presented to Vishwanath R by DigiDARA Technologies in March 2026" width={1840} height={3582} sizes="(max-width: 767px) 80vw, 240px" className="h-auto max-h-72 w-auto max-w-full rounded-lg object-contain md:max-h-80" /></Link><div><div className="icon-box mb-4 shrink-0"><Trophy className="h-5 w-5" /></div><h2 id="recognition-title" className="text-2xl font-semibold tracking-tight">AI Excellence Star Award</h2><p className="mt-1.5 text-sm font-medium text-primary">DigiDARA Technologies • March 2026</p><p className="mt-3 text-sm leading-7 text-muted-foreground">For sincere dedication and consistent excellence in AI project contributions.</p></div></Card></div></div></section> }

function Skills() { return <section id="skills" className="skills-section section-pad surface-band"><div className="container"><SectionHeading eyebrow="Technical Skills" title="AI depth with the engineering stack to ship complete applications." description="A focused view of the AI, retrieval, backend, data, application, and deployment technologies used across my work." /><div className="skills-grid grid items-start gap-4 md:grid-cols-2 xl:grid-cols-3">{skillGroups.map(({ title, icon: Icon, skills }) => <Card className="skill-category" key={title}><div className="flex items-center gap-3"><div className="icon-box small"><Icon className="h-4 w-4" /></div><h3 className="font-semibold tracking-tight">{title}</h3></div><div className="mt-5 flex flex-wrap gap-2">{skills.map(skill => <span className={primarySkills.has(skill) ? "tech-chip core-tech-chip" : "tech-chip"} key={skill}>{skill}</span>)}</div></Card>)}</div><div className="education-block mt-16"><SectionHeading eyebrow="Education" title="Data science and mathematics foundations." /><div className="mx-auto grid max-w-4xl gap-4 md:grid-cols-2">{education.map(item => <Card className="education-item" key={item.degree}><GraduationCap className="h-6 w-6 text-primary" /><h3 className="mt-5 text-lg font-semibold">{item.degree}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.institution}</p><p className="mt-5 border-t pt-4 text-sm font-medium text-primary">Graduated {item.year}</p></Card>)}</div></div></div></section> }

function Contact() { return <section id="contact" className="contact-section section-pad"><div className="container"><div className="contact-panel mx-auto max-w-5xl rounded-[2rem] p-7 sm:p-12 lg:p-16"><p className="eyebrow">Contact</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">Let’s build intelligent systems.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">I’m currently open to AI Engineer, Generative AI, and Agentic AI opportunities across the UAE.</p><div className="contact-actions mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link href={`mailto:${profile.email}`}>Email Me <Mail className="h-4 w-4" /></Link></Button>{contactActions.filter(a => a.label !== "Email").map(({ label, href, icon: Icon }) => <Button key={label} size="lg" variant="secondary" asChild><Link href={href} target="_blank" rel="noopener noreferrer"><Icon className="h-4 w-4" />{label}</Link></Button>)}</div></div></div></section> }

function StructuredData() { const data = { "@context": "https://schema.org", "@type": "Person", name: profile.name, jobTitle: profile.role, description: profile.specialization, address: { "@type": "PostalAddress", addressLocality: "Dubai", addressCountry: "AE" }, email: `mailto:${profile.email}`, url: "https://vishwanath-portfolio-flax.vercel.app", image: profile.avatar, sameAs: [profile.github, profile.linkedin], knowsAbout: tags }; return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} /> }

function Footer() { return <footer className="border-t py-9"><div className="container flex flex-col gap-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><p>© 2026 {profile.name}. AI Engineer in Dubai, UAE.</p><Link className="font-medium hover:text-foreground" href="#top">Back to top ↑</Link></div></footer> }

export function PortfolioPage() { return <><StructuredData /><div id="top"><Hero /></div><About /><Expertise /><Work /><Experience /><Recognition /><Skills /><Contact /><Footer /></> }
